apiVersion: v1
kind: Service
metadata:
  name: sf-webserver
spec:
  type: NodePort
  selector:
    app: nginx-sf  # Это должно совпадать с label подов
  ports:
    - protocol: TCP
      port: 80  # порт, который будет открыт на сервисе
      targetPort: 80  # порт, на который будет направлен трафик в подах
